### ISSUE TITLE
New Currency section needed

### ISSUE THREAD

**Issue by DITAWriter** [AgoraDoc/agora-style-guide#12]
(I suggest the following be added after the "Numbers" section in the existing Style Guide).

### Currency

Agora technical documentation rarely mentions currency figures, but they do occasionally come up in billing-related documentation. In English documentation, the standard currency used is in US dollars. Please keep the following in mind when writing currency information.

#### Using the dollar symbol and amounts
Always place the dollar symbol at the beginning of a currency value, followed by its currency code. For example: "$0.99 USD". 

If the amount is less than a full dollar, ensure that there is a leading 0 before the decimal point. Also, always use two decimal places for any dollar amount. For example "$9.90 USD", and not "$9.9 USD".

#### Referencing the currency
When referencing US dollars, it is not enough to use the dollar symbol ("$"), as there are other national currencies that also use the dollar, such as the Australian or Canadian dollars. When referencing US dollars, use the official ISO 4217 three-letter currency code, which is "USD". Use this same ISO standard if you need to refer to other currencies in your documentation.

**Comment by wangjie-agora** [comment]
Could you give us an example of using "USD"? Should it be used together with the dollar symbol or not?

**Comment by DITAWriter** [comment]
Let me amend my original proposal. I want to find the original piece that I edited so that I can present the context for use correctly. 
Cheers! 
    On Tuesday, July 7, 2020, 01:58:17 a.m. EDT, wangjie-agora <notifications@github.com> wrote:  
 
 


Could you give us an example of using "USD"? Should it be used together with the dollar symbol or not?

**Comment by DITAWriter** [comment]
### Currency
Agora technical documentation rarely mentions currency figures, but they do occasionally come up in billing-related documentation. In English documentation, the standard currency used is in US dollars. Please keep the following in mind when writing currency information.

#### Referencing the currency
When referencing US dollars, it is not enough to use the dollar symbol ("$"), as there are other national currencies that also use the dollar, such as the Australian or Canadian dollars. When referencing US dollars, use "$US". So long as an article references "$US" within the article and there are no other currencies referenced, it will be understood that "$" will mean "$US".

For example:

Service type | Pricing ($US/1,000 minutes)
-- | --
Recording audio | $1.49
Recording video | High-Definition (HD): $5.99
High-Definition Plus (HD+): $22.49

If you are writing about more than one type of currency within the same article, use the official [ISO 4217 three-letter currency code](https://www.thefinancials.com/Default.aspx?SubSectionID=curformat), which is "USD". Use this same ISO standard if you need to refer to other currencies in your documentation. The currency amount immediately follows the three-letter currency code with no intervening space. For large currency amounts, things are typically rounded to the nearest dollar, so there is no need to display the dollar amount to two decimal places. 

For example:
In Q4 the company posted a net profit of CNY1,234,567 (USD176,297). 

If it is understood through context that the currency is in US dollars, there is no need to use the three-letter ISO code.

For example:
The American division posted a net revenue of $123,456.

#### Using the dollar symbol and amounts
Always place the dollar symbol at the beginning of a currency value, without any intervening space. For example: "$0.99".

If the amount is less than a full dollar, ensure that there is a leading 0 before the decimal point. Also, when referring to the small figures that are used in billing documentation, always use two decimal places for any dollar amount. For example "$9.90", and not "$9.9".
