### ISSUE TITLE
Should we use "audience member" instead of "audience" when referring to an individual audience member?

### ISSUE THREAD

**Issue by yamasite** [AgoraDoc/agora-style-guide#14]
From Keith:

> I really want to advocate that “audience member” be used whenever there is the chance of possible confusion. When it is clear that it is the name of a role, then “member” can be dropped.

Should we add this to Agora Style Guide?

**Comment by DITAWriter** [comment]
Yes.
I think it makes sense to provide information about the context for what is going on here. When I look back on my earlier edits relating to the initial programming of these terms it was often paired with the word "role" which made sense in that context. "The audience role" and "the host role" makes sense when you are describing what they are. 
But what talking about scenarios describing how these roles are used, the assumption by most English readers will be that "audience" will be comprised of several people. While it is possible to have an audience of just one person, the assumption is that an audience is comprised of multiple people. Hence, it makes sense in the case of describing a scenario to say "audience member".
I hope that helps to make things clear. 
Cheers!
    On Tuesday, July 21, 2020, 07:18:51 a.m. EDT, Lutkin Wang <notifications@github.com> wrote:  
 
 


From Keith:


I really want to advocate that “audience member” be used whenever there is the chance of possible confusion. When it is clear that it is the name of a role, then “member” can be dropped.


Should we add this to Agora Style Guide?
