### ISSUE TITLE
Fix title of Section 3 of the style guide

### ISSUE THREAD

**Issue by mst3k4ever** [AgoraDoc/agora-style-guide#19]
It currently says "Punctuations"; it should just be "Punctuation". As a collective noun, it has no plural form. You could say "Punctuation Marks", but that would really just be for a list of the various punctuation marks. I think when you include rules for usage, you are under the wider umbrella of punctuation. 

Cheers,

Bill

**Comment by wangjie-agora** [comment]
Thanks for pointing this out. I will fix it with other issues in October.
BTW, we are on holiday for the mid-autumn festival and national holiday from October 1 to October 8, so the response may be slow.
