### ISSUE TITLE
Add an exception to our internal agreement on using "method"

### ISSUE THREAD

**Issue by lynnfirst** [AgoraDoc/agora-style-guide#7]
In the [Articles and internal agreement](https://agoradoc-style-guide.readthedocs.io/en/latest/language-and-grammar.html?highlight=method#articles-and-internal-agreement) section, we agree that there is no need to use “the” or even “method” when describing what a method does, as the reader will understand that it is a method by context. This rule particularly applies to a commonly-used phrase "call xxx". However, I think when a method is a subject, such as in the following sentence, it's better to keep "the"+"method", because it may be not clear whether it's a method or a callback. So I suggest adding an exception to this rule.

> The `getScreenSources` method is a wrapper of `desktopCapturer.getSources` provided by Electron. See [desktopCapturer](https://electronjs.org/docs/api/desktop-capturer).

**Comment by wangjie-agora** [comment]
Apart from "call xxx", are there other situations where the readers can tell if the API is a method or not?
If not, I think we need to make "call xxx" an exception and use "the xxx method" in most other cases.

**Comment by DITAWriter** [comment]
I ran across another example today where we ought to consider using "xxx method", and that was for the case of a third-party method. I think that that is a good exception to the rule as well, so long as it is specified that it is not an Agora method being referenced.
